version: '3.8'

services:
  # ============================================
  # INFRASTRUCTURE
  # ============================================

  redis:
    image: redis:7.2-alpine
    container_name: Careerhub-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: Careerhub-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 15s
      timeout: 10s
      retries: 3

  # ============================================
  # FRONTEND (Next.js)
  # ============================================

  frontend:
    build: .
    container_name: Careerhub-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_USE_GATEWAY: "true"
      NEXT_PUBLIC_API_GATEWAY_URL: "http://api-gateway:4000"
    depends_on:
      - api-gateway

  # ============================================
  # API GATEWAY
  # ============================================

  api-gateway:
    build:
     context: .
     dockerfile: services/api-gateway/Dockerfile
    container_name: Careerhub-gateway
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      GATEWAY_PORT: 4000
      REDIS_URL: redis://redis:6379
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      FRONTEND_URL: http://frontend:3000
      USER_SERVICE_URL: http://user-service:4001
      CONTENT_SERVICE_URL: http://content-service:4002
      NOTIFICATION_SERVICE_URL: http://notification-service:4003
      MESSAGING_SERVICE_URL: http://messaging-service:4004
      AI_SERVICE_URL: http://ai-service:4005
    depends_on:
      redis:
        condition: service_healthy

  # ============================================
  # USER SERVICE
  # ============================================
  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    container_name: Careerhub-user
    restart: unless-stopped
    ports:
      - "4001:4001"
    environment:
     USER_SERVICE_PORT: 4001
     DATABASE_URL: ${DATABASE_URL}
     JWT_SECRET_KEY: ${JWT_SECRET_KEY}
     RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
     rabbitmq:
      condition: service_healthy
  # ============================================
  # CONTENT SERVICE
  # ============================================

  content-service:
    build:
      context: .
      dockerfile: services/content-service/Dockerfile
    container_name: Careerhub-content
    restart: unless-stopped
    ports:
      - "4002:4002"
    environment:
      CONTENT_SERVICE_PORT: 4002
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  # ============================================
  # NOTIFICATION SERVICE
  # ============================================

  notification-service:
    build:
      context: .
      dockerfile: services/notification-service/Dockerfile
    container_name: Careerhub-notification
    restart: unless-stopped
    ports:
      - "4003:4003"
    environment:
      NOTIFICATION_SERVICE_PORT: 4003
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
    depends_on:
      rabbitmq:
        condition: service_healthy

  # ============================================
  # MESSAGING SERVICE
  # ============================================

  messaging-service:
    build:
      context: .
      dockerfile: services/messaging-service/Dockerfile
    container_name: Careerhub-messaging
    restart: unless-stopped
    ports:
      - "4004:4004"
    environment:
      MESSAGING_SERVICE_PORT: 4004
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  # ============================================
  # AI SERVICE
  # ============================================

  ai-service:
    build:
      context: .
      dockerfile: services/ai-service/Dockerfile
    container_name: Careerhub-ai
    restart: unless-stopped
    ports:
      - "4005:4005"
    environment:
      AI_SERVICE_PORT: 4005
      REDIS_URL: redis://redis:6379
      AI_PROVIDER: ${AI_PROVIDER}
      GROQ_API_KEY: ${GROQ_API_KEY}
      AI_MODEL_ID: ${AI_MODEL_ID}
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_data:
  rabbitmq_data: